[2021-06-10 17:41:15,015] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: my_dag.inaccurate 2021-06-09T00:00:00+00:00 [queued]>
[2021-06-10 17:41:15,028] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: my_dag.inaccurate 2021-06-09T00:00:00+00:00 [queued]>
[2021-06-10 17:41:15,029] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-06-10 17:41:15,029] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-06-10 17:41:15,032] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-06-10 17:41:15,044] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): inaccurate> on 2021-06-09T00:00:00+00:00
[2021-06-10 17:41:15,051] {standard_task_runner.py:52} INFO - Started process 658 to run task
[2021-06-10 17:41:15,055] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'inaccurate', '2021-06-09T00:00:00+00:00', '--job-id', '42', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/my_dags.py', '--cfg-path', '/tmp/tmp_50vb36o', '--error-file', '/tmp/tmpnkqk1wwc']
[2021-06-10 17:41:15,056] {standard_task_runner.py:77} INFO - Job 42: Subtask inaccurate
[2021-06-10 17:41:15,103] {logging_mixin.py:104} INFO - Running <TaskInstance: my_dag.inaccurate 2021-06-09T00:00:00+00:00 [running]> on host 1bd753f02904
[2021-06-10 17:41:15,158] {taskinstance.py:1282} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=inaccurate
AIRFLOW_CTX_EXECUTION_DATE=2021-06-09T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-06-09T00:00:00+00:00
[2021-06-10 17:41:15,159] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-06-10 17:41:15,161] {subprocess.py:63} INFO - Running command: ['bash', '-c', "echo 'inaccurate'"]
[2021-06-10 17:41:15,171] {subprocess.py:75} INFO - Output:
[2021-06-10 17:41:15,173] {subprocess.py:79} INFO - inaccurate
[2021-06-10 17:41:15,174] {subprocess.py:83} INFO - Command exited with return code 0
[2021-06-10 17:41:15,199] {taskinstance.py:1191} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=inaccurate, execution_date=20210609T000000, start_date=20210610T174115, end_date=20210610T174115
[2021-06-10 17:41:15,224] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-06-10 17:41:15,268] {local_task_job.py:151} INFO - Task exited with return code 0
